### ISSUE TITLE
Manual Links Leading to Library - Update

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#140]
# Manual Links Leading to Library - Update

Here's a quick process on how to deal with Manual links leading to the library.

There's two options:

* (1) A Manual link leads to a Library content, the Library content has an equivalent in the Manual
  * We adjust the Manual link to lead to the equivalent Manual content
* (2) A Manual link leads to a Library content, the Library content has NO equivalent in the Manual
  * We need to create/transfer the content from the Library to the Manual
  
The next comment of this issue will be to create a todo list of links that need to be updated (with tick box to show when the update is done on the Manual).
  
For both options, (1) and (2), we first gather the data here, then we can adjust the Manual accordingly. When a link is updated (with or without new content on the Manual), we will tick the related box in the list below.
  
  Feel free to comment/reply in this issue when you find such links (either option (1) or (2)), then we can track them all and update as we find them.
  
  ***
  
@amandacaster please don't hesitate to add the links/contents to be updated here!

**Comment by Mik-TF** [comment]
# Todo: Links to be Updated in TF Manual

Option (1): Library links with Manual equivalent

* [ ] [QnA from FAQ on Public Config](https://www2.manual.grid.tf/faq/faq.html#can-someone-explain-what-should-i-put-in-the-public-ip-part-of-my-farm-should-i-just-insert-my-public-ip-and-gateway-given-by-my-isp)
  *  [Library content](https://library.threefold.me/info/manual/#/manual__public_config)
  * [Manual equivalent](https://www2.manual.grid.tf/farmers/3node_building/1_create_farm.html#how-to-configure-public-ip-addresses-for-a-threefold-farm-or-a-3node) 

Option (2): Library links with NO Manual equivalent

* [ ] [QnA from FAQ on Yggdrasil](https://www2.manual.grid.tf/faq/faq.html#how-can-i-use-and-install-yggdrasil)
  * [Library content](https://library.threefold.me/info/manual/#/manual__yggdrasil_client)
* [ ] [QnA from FAQ on Farming rewards](https://www2.manual.grid.tf/faq/faq.html#what-is-the-farming-reward-calculation)
  * [Library content](https://library.threefold.me/info/threefold/#/tfgrid/farming/threefold__proof_of_capacity)
